create or alter view V_INVENTORIES as
select 
	INV.ID,STORE_LOC as STORE_LOCATION,INV.INV_DATETIME,INV.PERSON,SUM(III.ACTUAL_QTY * IEM.BASE_PRICE) as TOTAL_INVENTORY_VALUE
from ITEM_INV INV
	left join STORE STO on INV.STORE_CID = STO.CID
	left join ITEM_INV_LINE III on III.ITEM_INV_ID = INV.ID
	left join ITEM IEM on IEM.ID = III.ITEM_ID
group by INV.ID,STORE_LOC,INV.INV_DATETIME,INV.PERSON
go